# Generated by Django 3.1.3 on 2021-01-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Commit_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        
        
        migrations.CreateModel(
            name='Student_dengpei_yunpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('file_attach', models.FileField()),
                ('content', models.TextField()),
                ('commit_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Student_dengpei')),
            ],
        ),
    ]
